#!/bin/bash

echo "APP_STORE_CONNECT_ISSUER=${APP_STORE_CONNECT_ISSUER}" >> .env
echo "APP_STORE_CONNECT_APP_ID=${APP_STORE_CONNECT_APP_ID}" >> .env
echo "APP_STORE_CONNECT_API_KEY=${APP_STORE_CONNECT_API_KEY}" >> .env
echo "PLATFORM=${PLATFORM}" >> .env