name: Test build

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request: {}

jobs:
  build-macOS-AppStore:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Build macOS
        run: xcodebuild -quiet -workspace Vocaltale.xcworkspace -scheme "Vocaltale (macOS, App Store)" -configuration Debug build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  build-macOS:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Build macOS
        run: xcodebuild -quiet -workspace Vocaltale.xcworkspace -scheme "Vocaltale (macOS)" -configuration Debug build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  build-iOS:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Build iOS
        run: xcodebuild -quiet -workspace Vocaltale.xcworkspace -scheme "Vocaltale (iOS)" -configuration Debug build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
